### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by GrayTempest-400** [PenUniverse/PenMods-release#256]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

Installer (安装程序)

### 词典笔型号

YDPG-3

### PenMods 版本

1.20

### 词典笔系统版本

4.0.2

### 发生了什么?

D:\SDE\Anaconda\Anaconda3\envs\tensorrt\python.exe C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py 
┌───────────────────────────────────┐
│                                   │
│       ╔═╗┌─┐┌┐┌╔╦╗┌─┐┌┬┐┌─┐       │
│       ╠═╝├┤ │││║║║│ │ ││└─┐       │
│       ╩  └─┘┘└┘╩ ╩└─┘─┴┘└─┘       │
│                                   │
└───────────────────────────────────┘
Welcome to use PenMods!
Developer:  RedbeanW
Repo:       https://github.com/PenUniverse/Installer
Version:    1.1.0
Traceback (most recent call last):
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py", line 289, in <module>
    handleAssert(checkConnection(), '安装程序需要联网执行，请检查您的网络链接。')
  File "C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py", line 210, in checkConnection
    return requests.get(PENMODS_SERVER_ADDR,verify=False).status_code == 200
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

### 复现此问题的步骤

网络正常，运行下载.exe和下载.py的文件都会报错，防火墙和梯子都关了

**Comment by GrayTempest-400** [comment]
D:\SDE\Anaconda\Anaconda3\envs\tensorrt\python.exe C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py 
┌───────────────────────────────────┐
│                                   │
│       ╔═╗┌─┐┌┐┌╔╦╗┌─┐┌┬┐┌─┐       │
│       ╠═╝├┤ │││║║║│ │ ││└─┐       │
│       ╩  └─┘┘└┘╩ ╩└─┘─┴┘└─┘       │
│                                   │
└───────────────────────────────────┘
Welcome to use PenMods!
Developer:  RedbeanW
Repo:       https://github.com/PenUniverse/Installer
Version:    1.1.0
Traceback (most recent call last):
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py", line 289, in <module>
    handleAssert(checkConnection(), '安装程序需要联网执行，请检查您的网络链接。')
  File "C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py", line 210, in checkConnection
    return requests.get(PENMODS_SERVER_ADDR,verify=False).status_code == 200
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by GrayTempest-400** [comment]
D:\SDE\Anaconda\Anaconda3\envs\tensorrt\python.exe C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py 
┌───────────────────────────────────┐
│                                   │
│       ╔═╗┌─┐┌┐┌╔╦╗┌─┐┌┬┐┌─┐       │
│       ╠═╝├┤ │││║║║│ │ ││└─┐       │
│       ╩  └─┘┘└┘╩ ╩└─┘─┴┘└─┘       │
│                                   │
└───────────────────────────────────┘
Welcome to use PenMods!
Developer:  RedbeanW
Repo:       https://github.com/PenUniverse/Installer
Version:    1.1.0
Traceback (most recent call last):
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connection.py", line 206, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000024672D4BD90>: Failed to resolve 'dictpen.amd.rocks' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dictpen.amd.rocks', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024672D4BD90>: Failed to resolve 'dictpen.amd.rocks' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py", line 289, in <module>
    handleAssert(checkConnection(), '安装程序需要联网执行，请检查您的网络链接。')
  File "C:\Users\诗乃琴音\Desktop\Installer-main\Installer.py", line 210, in checkConnection
    return requests.get(PENMODS_SERVER_ADDR,verify=False).status_code == 200
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\SDE\Anaconda\Anaconda3\envs\tensorrt\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dictpen.amd.rocks', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024672D4BD90>: Failed to resolve 'dictpen.amd.rocks' ([Errno 11001] getaddrinfo failed)"))

进程已结束,退出代码1
这是不使用代理的情况

**Comment by GrayTempest-400** [comment]
是不是你们服务器忘开了，直接访问也访问不了

**Comment by Redbeanw44602** [comment]
#247

**Comment by GrayTempest-400** [comment]
你们tg群连接呢

**Comment by Redbeanw44602** [comment]
在 README...
